language: node_js
node_js:
  - 0.10
  - 0.12
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
os:
  - linux
  - osx
script: "function timeout() { perl -e 'alarm shift; exec @ARGV' \"$@\"; }; npm install && timeout 10 ./bin/chromedriver || test $? -eq 142"
